### ISSUE TITLE
Cant get it installed.

### ISSUE THREAD

**Issue by o0oradaro0o** [FarisHijazi/PrivateGitHubCopilot#3]
followed the instructions and got the following error:

``` 
Collecting git+https://github.com/FarisHijazi/PrivateGitHubCopilot
  Cloning https://github.com/FarisHijazi/PrivateGitHubCopilot to c:\users\lvana\appdata\local\temp\pip-req-build-p48_4g0k
  Running command git clone --filter=blob:none --quiet https://github.com/FarisHijazi/PrivateGitHubCopilot 'C:\Users\lvana\AppData\Local\Temp\pip-req-build-p48_4g0k'
  Resolved https://github.com/FarisHijazi/PrivateGitHubCopilot to commit ce5f2a5fca48d3ad894cacf6937439cb6fb2c893
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.      
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lvana\AppData\Local\Temp\pip-req-build-p48_4g0k\setup.py", line 8, in <module>
          long_description = fh.read().replace('](', '](https://raw.githubusercontent.com/FarisHijazi/PrivateGitHubCopilot/master/')
        File "C:\Users\lvana\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 955: character maps to <undefined>
      [end of output]
``` 

figured maybe you weren't on windows and it was just an encoding problem but when i forked the repo and made a new setup that included utf 8 encoding. The install seems to work but the middleware module is not being found when i try the run command

PrivateGitHubCopilot --port 8000

I get
``` 
Traceback (most recent call last):
  File "C:\Users\lvana\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lvana\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\lvana\AppData\Local\Programs\Python\Python310\Scripts\PrivateGitHubCopilot.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'middleware'
``` 
too sleepy now to figure it out so posting to bring it to your attention to see if you know how I'm being silly. 

thanks for making this!

**Comment by o0oradaro0o** [comment]
okay got it up and running on windows closing this and reopening my PR, hopefully it doesnt break on other OSs, it shouldnt
